[build]
  functions = "functions/"
  command = "cp functions/yt-dlp.exe . && npm run build"
  publish = "public"

[[redirects]]
  from = "/captions/*"
  to = "/.netlify/functions/captions/:splat"
  status = 200