[build]
  functions = "functions/"

[[redirects]]
  from = "/captions/*"
  to = "/.netlify/functions/captions/:splat"
  status = 200

  [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"